
# Monitoring
spring.jmx.enabled: true
management:
  endpoints.jmx.exposure.include: "*"
  endpoints.web.exposure.include: "*"
  metrics.kafka.consumer.enabled: true
  metrics.kafka.producer.enabled: true
  server.port: ${kafka.monitoring_port}
  

   
  

   
